# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xQW9v6xyC5XyRbuOyJe9o1tVZzCI1NRe
"""

import pandas as pd

baza = {
    "FISH": ["ALIYEVA DINORA", "VALIYEV VALI", "ABDULLAYEV ABDUL", "XOLIQOVA ZARINA", "YUSUPOVA NIGORA",
             "HASANOV BEKZOD", "ALIYEV UMID", "JUMAYEV SHERZOD", "XOLIQOV ABDULLO", "YOQUBOV MANSUR",
             "XOLIQOVA SARVINOZ", "NURMATOV DILSHOD"],
    "YOSHI": ['11', '16', '12', '15', '13', '14', '11', '12', '15', '13', '12', '16'],
    "JINSI": ['qiz bola', "og'il bola", "og'il bola", 'qiz bola', 'qiz bola', "og'il bola", "og'il bola",
              "og'il bola", "og'il bola", 'qiz bola', 'qiz bola', "og'il bola"],
    "QAYSI MAKTAB": ['2', 'Prizident Maktabi', '5', '12', '10', '7', 'Prizident Maktabi', '8', '3', '11', '6', '2']
}

df = pd.DataFrame(baza)


print(df)

filtered_df = df[df['YOSHI'].astype(int) > 12]
print("\nFiltered Data (YOSHI > 12):")
print(filtered_df)

filteredjinsi_df = df[df['JINSI']=="og'il bola"]
print("\nFiltered Data (OG'IL BOLA):")
print(filteredjinsi_df)

filteredjinsage_df = df[(df['YOSHI'].astype(int) < 15) & (df['JINSI'] == "og'il bola")]
print("\nFiltered Data (OG'IL BOLA va 15 yoshdan kichik):")
print(filteredjinsage_df)

filteremin_age_index = df['YOSHI'].astype(int).idxmin()
filteremin_age_row = df.loc[filteremin_age_index]
print("\nFiltered Data (ENG KICHIK YOSH):")
print(filteremin_age_row)